# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Do You Know The Muffin Man?
description:      'I like to bake and make desserts in my spare time. This is a journal of my experiments.'
url:              http://www.gnufmuffin.com/

author:
  name:           'Eric Fung'
  url:            https://twitter.com/gnufmuffin
